# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Builds -> skywalking-agent:latest-e2e
ARG BASE_PYTHON_IMAGE

FROM python:${BASE_PYTHON_IMAGE}

VOLUME /services

COPY tests/e2e/base/consumer/* /services/
COPY tests/e2e/base/provider/* /services/

# Copy the project and build
COPY . /skywalking-python/
RUN cd /skywalking-python && apt-get update && apt-get install -y make gcc && make install

# Extra dependencies for e2e services
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential\
    && rm -rf /var/lib/apt/lists/*
RUN pip install grpcio==1.57.0 grpcio-tools==1.57.0 packaging==23.1 protobuf==4.24.2  \
    aiohttp==3.8.5 "aiokafka<=0.8.1" aiosignal==1.3.1 async-timeout==4.0.3 attrs==23.1.0 \
    certifi==2023.7.22 charset-normalizer==3.2.0 "frozenlist<=1.4.0" idna==3.4 kafka-python==2.0.2 multidict==6.0.4 \
    psutil==5.9.5 requests==2.31.0 urllib3==2.0.4 "flask<=2.3.3" "Werkzeug<=2.3.7" anyio==3.7.1 \
    Jinja2==3.1.2 MarkupSafe==2.1.3 annotated-types==0.5.0 anyio==3.7.1 blinker==1.6.2 click==8.1.7 \
    exceptiongroup==1.1.3 fastapi==0.103.0 gunicorn==21.2.0 h11==0.14.0 "importlib-metadata<=6.8.0" \
    itsdangerous==2.1.2 pydantic==2.3.0 pydantic-core==2.6.3 sniffio==1.3.0 starlette==0.27.0 \
    typing-extensions==4.7.1 "uvicorn<=0.23.2" uwsgi==2.0.22 "zipp<=3.16.2" \
    && apt-get purge -y --auto-remove gcc build-essential

# Entrypoint with agent attached
WORKDIR /services

Entrypoint ["sw-python"]
